## Append samples of your project ##
resources:
- polaris_v1alpha1_polarisconnection.yaml
- polaris_v1alpha1_polariscatalog.yaml
- polaris_v1alpha1_polarisnamespace.yaml
- polaris_v1alpha1_polaristable.yaml
- polaris_v1alpha1_polarisview.yaml
- polaris_v1alpha1_polarispolicy.yaml
- polaris_v1alpha1_polarisprincipal.yaml
- polaris_v1alpha1_polarisprincipalrole.yaml
- polaris_v1alpha1_polariscatalogrole.yaml
- polaris_v1alpha1_polarisprincipalrolebinding.yaml
- polaris_v1alpha1_polariscatalogrolebinding.yaml
- polaris_v1alpha1_polarisgrant.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
