apiVersion: polaris.k8s.calific.io/v1alpha1
kind: PolarisPrincipalRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: polaris-k8s
    app.kubernetes.io/managed-by: kustomize
  name: polarisprincipalrolebinding-sample
spec:
  # TODO(user): Add fields here
