//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorageConfig) DeepCopyInto(out *AzureStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorageConfig.
func (in *AzureStorageConfig) DeepCopy() *AzureStorageConfig {
	if in == nil {
		return nil
	}
	out := new(AzureStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CABundleSecretRef) DeepCopyInto(out *CABundleSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CABundleSecretRef.
func (in *CABundleSecretRef) DeepCopy() *CABundleSecretRef {
	if in == nil {
		return nil
	}
	out := new(CABundleSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogRef) DeepCopyInto(out *CatalogRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogRef.
func (in *CatalogRef) DeepCopy() *CatalogRef {
	if in == nil {
		return nil
	}
	out := new(CatalogRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogRoleRef) DeepCopyInto(out *CatalogRoleRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogRoleRef.
func (in *CatalogRoleRef) DeepCopy() *CatalogRoleRef {
	if in == nil {
		return nil
	}
	out := new(CatalogRoleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientCredentialsSecretRef) DeepCopyInto(out *ClientCredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientCredentialsSecretRef.
func (in *ClientCredentialsSecretRef) DeepCopy() *ClientCredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(ClientCredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionRef) DeepCopyInto(out *ConnectionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionRef.
func (in *ConnectionRef) DeepCopy() *ConnectionRef {
	if in == nil {
		return nil
	}
	out := new(ConnectionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSStorageConfig) DeepCopyInto(out *GCSStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSStorageConfig.
func (in *GCSStorageConfig) DeepCopy() *GCSStorageConfig {
	if in == nil {
		return nil
	}
	out := new(GCSStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedCredentialsSecretRef) DeepCopyInto(out *GeneratedCredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedCredentialsSecretRef.
func (in *GeneratedCredentialsSecretRef) DeepCopy() *GeneratedCredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(GeneratedCredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrantTarget) DeepCopyInto(out *GrantTarget) {
	*out = *in
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(NamespaceRef)
		**out = **in
	}
	if in.TableRef != nil {
		in, out := &in.TableRef, &out.TableRef
		*out = new(TableRef)
		**out = **in
	}
	if in.ViewRef != nil {
		in, out := &in.ViewRef, &out.ViewRef
		*out = new(ViewRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrantTarget.
func (in *GrantTarget) DeepCopy() *GrantTarget {
	if in == nil {
		return nil
	}
	out := new(GrantTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergField) DeepCopyInto(out *IcebergField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergField.
func (in *IcebergField) DeepCopy() *IcebergField {
	if in == nil {
		return nil
	}
	out := new(IcebergField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergPartitionField) DeepCopyInto(out *IcebergPartitionField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergPartitionField.
func (in *IcebergPartitionField) DeepCopy() *IcebergPartitionField {
	if in == nil {
		return nil
	}
	out := new(IcebergPartitionField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergPartitionSpec) DeepCopyInto(out *IcebergPartitionSpec) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]IcebergPartitionField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergPartitionSpec.
func (in *IcebergPartitionSpec) DeepCopy() *IcebergPartitionSpec {
	if in == nil {
		return nil
	}
	out := new(IcebergPartitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergSchema) DeepCopyInto(out *IcebergSchema) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]IcebergField, len(*in))
		copy(*out, *in)
	}
	if in.IdentifierFieldIds != nil {
		in, out := &in.IdentifierFieldIds, &out.IdentifierFieldIds
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergSchema.
func (in *IcebergSchema) DeepCopy() *IcebergSchema {
	if in == nil {
		return nil
	}
	out := new(IcebergSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRef) DeepCopyInto(out *NamespaceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRef.
func (in *NamespaceRef) DeepCopy() *NamespaceRef {
	if in == nil {
		return nil
	}
	out := new(NamespaceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalog) DeepCopyInto(out *PolarisCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalog.
func (in *PolarisCatalog) DeepCopy() *PolarisCatalog {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogList) DeepCopyInto(out *PolarisCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogList.
func (in *PolarisCatalogList) DeepCopy() *PolarisCatalogList {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRole) DeepCopyInto(out *PolarisCatalogRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRole.
func (in *PolarisCatalogRole) DeepCopy() *PolarisCatalogRole {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisCatalogRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRoleBinding) DeepCopyInto(out *PolarisCatalogRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRoleBinding.
func (in *PolarisCatalogRoleBinding) DeepCopy() *PolarisCatalogRoleBinding {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisCatalogRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRoleBindingList) DeepCopyInto(out *PolarisCatalogRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisCatalogRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRoleBindingList.
func (in *PolarisCatalogRoleBindingList) DeepCopy() *PolarisCatalogRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisCatalogRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRoleBindingSpec) DeepCopyInto(out *PolarisCatalogRoleBindingSpec) {
	*out = *in
	out.PrincipalRoleRef = in.PrincipalRoleRef
	out.CatalogRoleRef = in.CatalogRoleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRoleBindingSpec.
func (in *PolarisCatalogRoleBindingSpec) DeepCopy() *PolarisCatalogRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRoleBindingStatus) DeepCopyInto(out *PolarisCatalogRoleBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRoleBindingStatus.
func (in *PolarisCatalogRoleBindingStatus) DeepCopy() *PolarisCatalogRoleBindingStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRoleBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRoleList) DeepCopyInto(out *PolarisCatalogRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisCatalogRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRoleList.
func (in *PolarisCatalogRoleList) DeepCopy() *PolarisCatalogRoleList {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisCatalogRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRoleSpec) DeepCopyInto(out *PolarisCatalogRoleSpec) {
	*out = *in
	out.CatalogRef = in.CatalogRef
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRoleSpec.
func (in *PolarisCatalogRoleSpec) DeepCopy() *PolarisCatalogRoleSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogRoleStatus) DeepCopyInto(out *PolarisCatalogRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogRoleStatus.
func (in *PolarisCatalogRoleStatus) DeepCopy() *PolarisCatalogRoleStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogSpec) DeepCopyInto(out *PolarisCatalogSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	in.StorageConfig.DeepCopyInto(&out.StorageConfig)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogSpec.
func (in *PolarisCatalogSpec) DeepCopy() *PolarisCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisCatalogStatus) DeepCopyInto(out *PolarisCatalogStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisCatalogStatus.
func (in *PolarisCatalogStatus) DeepCopy() *PolarisCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisConnection) DeepCopyInto(out *PolarisConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisConnection.
func (in *PolarisConnection) DeepCopy() *PolarisConnection {
	if in == nil {
		return nil
	}
	out := new(PolarisConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisConnectionList) DeepCopyInto(out *PolarisConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisConnectionList.
func (in *PolarisConnectionList) DeepCopy() *PolarisConnectionList {
	if in == nil {
		return nil
	}
	out := new(PolarisConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisConnectionSpec) DeepCopyInto(out *PolarisConnectionSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.CABundleSecretRef != nil {
		in, out := &in.CABundleSecretRef, &out.CABundleSecretRef
		*out = new(CABundleSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisConnectionSpec.
func (in *PolarisConnectionSpec) DeepCopy() *PolarisConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisConnectionStatus) DeepCopyInto(out *PolarisConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisConnectionStatus.
func (in *PolarisConnectionStatus) DeepCopy() *PolarisConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisGrant) DeepCopyInto(out *PolarisGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisGrant.
func (in *PolarisGrant) DeepCopy() *PolarisGrant {
	if in == nil {
		return nil
	}
	out := new(PolarisGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisGrantList) DeepCopyInto(out *PolarisGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisGrantList.
func (in *PolarisGrantList) DeepCopy() *PolarisGrantList {
	if in == nil {
		return nil
	}
	out := new(PolarisGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisGrantSpec) DeepCopyInto(out *PolarisGrantSpec) {
	*out = *in
	out.CatalogRoleRef = in.CatalogRoleRef
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisGrantSpec.
func (in *PolarisGrantSpec) DeepCopy() *PolarisGrantSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisGrantStatus) DeepCopyInto(out *PolarisGrantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisGrantStatus.
func (in *PolarisGrantStatus) DeepCopy() *PolarisGrantStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisNamespace) DeepCopyInto(out *PolarisNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisNamespace.
func (in *PolarisNamespace) DeepCopy() *PolarisNamespace {
	if in == nil {
		return nil
	}
	out := new(PolarisNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisNamespaceList) DeepCopyInto(out *PolarisNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisNamespaceList.
func (in *PolarisNamespaceList) DeepCopy() *PolarisNamespaceList {
	if in == nil {
		return nil
	}
	out := new(PolarisNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisNamespaceSpec) DeepCopyInto(out *PolarisNamespaceSpec) {
	*out = *in
	out.CatalogRef = in.CatalogRef
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(NamespaceRef)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisNamespaceSpec.
func (in *PolarisNamespaceSpec) DeepCopy() *PolarisNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisNamespaceStatus) DeepCopyInto(out *PolarisNamespaceStatus) {
	*out = *in
	if in.FullPath != nil {
		in, out := &in.FullPath, &out.FullPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisNamespaceStatus.
func (in *PolarisNamespaceStatus) DeepCopy() *PolarisNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPolicy) DeepCopyInto(out *PolarisPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPolicy.
func (in *PolarisPolicy) DeepCopy() *PolarisPolicy {
	if in == nil {
		return nil
	}
	out := new(PolarisPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPolicyList) DeepCopyInto(out *PolarisPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPolicyList.
func (in *PolarisPolicyList) DeepCopy() *PolarisPolicyList {
	if in == nil {
		return nil
	}
	out := new(PolarisPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPolicySpec) DeepCopyInto(out *PolarisPolicySpec) {
	*out = *in
	out.NamespaceRef = in.NamespaceRef
	in.Content.DeepCopyInto(&out.Content)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPolicySpec.
func (in *PolarisPolicySpec) DeepCopy() *PolarisPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolarisPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPolicyStatus) DeepCopyInto(out *PolarisPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPolicyStatus.
func (in *PolarisPolicyStatus) DeepCopy() *PolarisPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipal) DeepCopyInto(out *PolarisPrincipal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipal.
func (in *PolarisPrincipal) DeepCopy() *PolarisPrincipal {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPrincipal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalList) DeepCopyInto(out *PolarisPrincipalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisPrincipal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalList.
func (in *PolarisPrincipalList) DeepCopy() *PolarisPrincipalList {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPrincipalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRole) DeepCopyInto(out *PolarisPrincipalRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRole.
func (in *PolarisPrincipalRole) DeepCopy() *PolarisPrincipalRole {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPrincipalRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRoleBinding) DeepCopyInto(out *PolarisPrincipalRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRoleBinding.
func (in *PolarisPrincipalRoleBinding) DeepCopy() *PolarisPrincipalRoleBinding {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPrincipalRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRoleBindingList) DeepCopyInto(out *PolarisPrincipalRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisPrincipalRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRoleBindingList.
func (in *PolarisPrincipalRoleBindingList) DeepCopy() *PolarisPrincipalRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPrincipalRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRoleBindingSpec) DeepCopyInto(out *PolarisPrincipalRoleBindingSpec) {
	*out = *in
	out.PrincipalRef = in.PrincipalRef
	out.PrincipalRoleRef = in.PrincipalRoleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRoleBindingSpec.
func (in *PolarisPrincipalRoleBindingSpec) DeepCopy() *PolarisPrincipalRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRoleBindingStatus) DeepCopyInto(out *PolarisPrincipalRoleBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRoleBindingStatus.
func (in *PolarisPrincipalRoleBindingStatus) DeepCopy() *PolarisPrincipalRoleBindingStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRoleBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRoleList) DeepCopyInto(out *PolarisPrincipalRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisPrincipalRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRoleList.
func (in *PolarisPrincipalRoleList) DeepCopy() *PolarisPrincipalRoleList {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisPrincipalRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRoleSpec) DeepCopyInto(out *PolarisPrincipalRoleSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRoleSpec.
func (in *PolarisPrincipalRoleSpec) DeepCopy() *PolarisPrincipalRoleSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalRoleStatus) DeepCopyInto(out *PolarisPrincipalRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalRoleStatus.
func (in *PolarisPrincipalRoleStatus) DeepCopy() *PolarisPrincipalRoleStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalSpec) DeepCopyInto(out *PolarisPrincipalSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalSpec.
func (in *PolarisPrincipalSpec) DeepCopy() *PolarisPrincipalSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisPrincipalStatus) DeepCopyInto(out *PolarisPrincipalStatus) {
	*out = *in
	if in.CredentialsLastRotated != nil {
		in, out := &in.CredentialsLastRotated, &out.CredentialsLastRotated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisPrincipalStatus.
func (in *PolarisPrincipalStatus) DeepCopy() *PolarisPrincipalStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisPrincipalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisTable) DeepCopyInto(out *PolarisTable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisTable.
func (in *PolarisTable) DeepCopy() *PolarisTable {
	if in == nil {
		return nil
	}
	out := new(PolarisTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisTable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisTableList) DeepCopyInto(out *PolarisTableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisTableList.
func (in *PolarisTableList) DeepCopy() *PolarisTableList {
	if in == nil {
		return nil
	}
	out := new(PolarisTableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisTableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisTableSpec) DeepCopyInto(out *PolarisTableSpec) {
	*out = *in
	out.NamespaceRef = in.NamespaceRef
	in.Schema.DeepCopyInto(&out.Schema)
	if in.PartitionSpec != nil {
		in, out := &in.PartitionSpec, &out.PartitionSpec
		*out = new(IcebergPartitionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisTableSpec.
func (in *PolarisTableSpec) DeepCopy() *PolarisTableSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisTableStatus) DeepCopyInto(out *PolarisTableStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisTableStatus.
func (in *PolarisTableStatus) DeepCopy() *PolarisTableStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisTableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisView) DeepCopyInto(out *PolarisView) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisView.
func (in *PolarisView) DeepCopy() *PolarisView {
	if in == nil {
		return nil
	}
	out := new(PolarisView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisView) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisViewList) DeepCopyInto(out *PolarisViewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarisView, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisViewList.
func (in *PolarisViewList) DeepCopy() *PolarisViewList {
	if in == nil {
		return nil
	}
	out := new(PolarisViewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarisViewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisViewSpec) DeepCopyInto(out *PolarisViewSpec) {
	*out = *in
	out.NamespaceRef = in.NamespaceRef
	in.Schema.DeepCopyInto(&out.Schema)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisViewSpec.
func (in *PolarisViewSpec) DeepCopy() *PolarisViewSpec {
	if in == nil {
		return nil
	}
	out := new(PolarisViewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarisViewStatus) DeepCopyInto(out *PolarisViewStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarisViewStatus.
func (in *PolarisViewStatus) DeepCopy() *PolarisViewStatus {
	if in == nil {
		return nil
	}
	out := new(PolarisViewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalRef) DeepCopyInto(out *PrincipalRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalRef.
func (in *PrincipalRef) DeepCopy() *PrincipalRef {
	if in == nil {
		return nil
	}
	out := new(PrincipalRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrincipalRoleRef) DeepCopyInto(out *PrincipalRoleRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrincipalRoleRef.
func (in *PrincipalRoleRef) DeepCopy() *PrincipalRoleRef {
	if in == nil {
		return nil
	}
	out := new(PrincipalRoleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3StorageConfig) DeepCopyInto(out *S3StorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3StorageConfig.
func (in *S3StorageConfig) DeepCopy() *S3StorageConfig {
	if in == nil {
		return nil
	}
	out := new(S3StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.AllowedLocations != nil {
		in, out := &in.AllowedLocations, &out.AllowedLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3StorageConfig)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureStorageConfig)
		**out = **in
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(GCSStorageConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableRef) DeepCopyInto(out *TableRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableRef.
func (in *TableRef) DeepCopy() *TableRef {
	if in == nil {
		return nil
	}
	out := new(TableRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewRef) DeepCopyInto(out *ViewRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewRef.
func (in *ViewRef) DeepCopy() *ViewRef {
	if in == nil {
		return nil
	}
	out := new(ViewRef)
	in.DeepCopyInto(out)
	return out
}
