# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/polaris.k8s.calific.io_polarisconnections.yaml
- bases/polaris.k8s.calific.io_polariscatalogs.yaml
- bases/polaris.k8s.calific.io_polarisnamespaces.yaml
- bases/polaris.k8s.calific.io_polaristables.yaml
- bases/polaris.k8s.calific.io_polarisviews.yaml
- bases/polaris.k8s.calific.io_polarispolicies.yaml
- bases/polaris.k8s.calific.io_polarisprincipals.yaml
- bases/polaris.k8s.calific.io_polarisprincipalroles.yaml
- bases/polaris.k8s.calific.io_polariscatalogroles.yaml
- bases/polaris.k8s.calific.io_polarisprincipalrolebindings.yaml
- bases/polaris.k8s.calific.io_polariscatalogrolebindings.yaml
- bases/polaris.k8s.calific.io_polarisgrants.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
